name: Flaky Test Detector Alternative

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest lxml

      - name: First test run
        id: first_run
        continue-on-error: true
        run: |
          mkdir -p test-results
          pytest test/unittest/test_flaky.py \
            --tb=short \
            --junitxml=test-results/results-1.xml

      - name: Check first run result
        if: steps.first_run.outcome == 'success'
        run: echo "First run passed, no flakiness detected."

      - name: Second test run (only if first run failed)
        id: second_run
        if: steps.first_run.outcome != 'success'
        continue-on-error: true
        run: |
          pytest test/unittest/test_flaky.py \
            --tb=short \
            --junitxml=test-results/results-2.xml

      - name: Fail if second run fails
        if: steps.second_run.outcome != 'success'
        run: |
          echo "Test failed again. Not flaky — real failure."
          exit 1

      - name: Upload test results
        if: steps.second_run.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Checkout flaky analysis script repo
        if: steps.second_run.outcome == 'success'
        uses: actions/checkout@v4
        with:
          repository: jiz17043/detect_flaky

      - name: Detect flaky tests
        if: steps.second_run.outcome == 'success'
        run: |
          python scripts/detect_flaky_tests2.py
